import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { CheckCircle2, XCircle, RefreshCw, TrendingUp, AlertCircle } from 'lucide-react'
import { proposalsApi, blogApi } from '@/services/api'

/**
 * FeedbackProposals (PR #7) — human review surface for Blueprint update
 * proposals generated by the feedback engine.
 *
 * Lists pending proposals with full evidence (sample size, effect size,
 * confidence interval, articles used). The user can accept or reject each.
 *
 * On accept: the backend creates a new Blueprint version and fans out
 * per-article improvement proposals to all published articles in the niche.
 * A "View published articles" link routes to the Published Articles list.
 */
const FeedbackProposals = () => {
  const [proposals, setProposals] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [busy, setBusy] = useState(null)   // proposal id being accepted/rejected
  const [tab, setTab] = useState('pending')
  const [niches, setNiches] = useState([])

  const refresh = async () => {
    setLoading(true)
    setError(null)
    try {
      const [pRes, nRes] = await Promise.all([
        proposalsApi.list({ status: tab, limit: 100 }),
        blogApi.getNiches(),
        ])
      if (pRes.success) setProposals(pRes.proposals || [])
      else setError(pRes.error || 'Failed to load proposals.')
      if (nRes.success) setNiches(nRes.niches || [])
    } catch (err) {
      setError(err.message || 'Network error.')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { refresh() }, [tab])

  const nicheNameFor = (id) => niches.find(n => n.id === id)?.name || `Niche ${id}`

  const handleAccept = async (id) => {
    setBusy(id)
    try {
      const res = await proposalsApi.accept(id)
      if (res.success) {
        await refresh()
      } else {
        alert(`Accept failed: ${res.error}`)
      }
    } catch (err) {
      alert(`Error: ${err.message}`)
    } finally {
      setBusy(null)
    }
  }

  const handleReject = async (id) => {
    if (!confirm('Reject this proposal? The current Blueprint will not change.')) return
    setBusy(id)
    try {
      const res = await proposalsApi.reject(id)
      if (res.success) await refresh()
      else alert(`Reject failed: ${res.error}`)
    } catch (err) {
      alert(`Error: ${err.message}`)
    } finally {
      setBusy(null)
    }
  }

  const handleGenerate = async (nicheId) => {
    setBusy(`gen-${nicheId}`)
    try {
      const res = await proposalsApi.generate(nicheId)
      if (res.success) {
        await refresh()
        alert(`Generated ${res.proposals_created} new proposal(s).`)
      } else {
        alert(`Generate failed: ${res.error}`)
      }
    } catch (err) {
      alert(`Error: ${err.message}`)
    } finally {
      setBusy(null)
    }
  }

  const fieldLabel = (field) =>
    field
      .replace(/_/g, ' ')
      .replace(/\b\w/g, (c) => c.toUpperCase())

  const formatValue = (val) => {
    if (val === null || val === undefined) return '—'
    if (Array.isArray(val)) return val.join(' – ')
    if (typeof val === 'boolean') return val ? 'Yes' : 'No'
    return String(val)
  }

  const effectBadge = (ev) => {
    const e = Math.abs(ev?.effect_size ?? 0)
    if (e >= 0.3) return <Badge className="bg-red-100 text-red-800">Strong ({(e * 100).toFixed(0)}%)</Badge>
    if (e >= 0.1) return <Badge className="bg-yellow-100 text-yellow-800">Moderate ({(e * 100).toFixed(0)}%)</Badge>
    return <Badge className="bg-gray-100 text-gray-700">Weak ({(e * 100).toFixed(0)}%)</Badge>
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Blueprint Proposals</h1>
          <p className="text-sm text-gray-500 mt-1">
            Evidence-based suggestions to improve your content Blueprint. Accept to apply;
            reject to keep the current Blueprint unchanged.
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={refresh} disabled={loading}>
          <RefreshCw className={`h-4 w-4 mr-2 ${loading ? 'animate-spin' : ''}`} />
          Refresh
        </Button>
      </div>

      {error && (
        <div className="flex items-center gap-2 text-red-600 bg-red-50 rounded p-3 text-sm">
          <AlertCircle className="h-4 w-4 flex-shrink-0" />
          {error}
        </div>
      )}

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList>
          <TabsTrigger value="pending">Pending</TabsTrigger>
          <TabsTrigger value="accepted">Accepted</TabsTrigger>
          <TabsTrigger value="rejected">Rejected</TabsTrigger>
        </TabsList>

        <TabsContent value={tab} className="mt-4">
          {loading ? (
            <p className="text-sm text-gray-500">Loading…</p>
          ) : proposals.length === 0 ? (
            <Card>
              <CardContent className="py-10 text-center text-gray-500 text-sm">
                No {tab} proposals.
                {tab === 'pending' && (
                  <p className="mt-2">
                    Run the feedback engine via the niche page to generate new proposals.
                  </p>
                )}
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-4">
              {proposals.map((p) => {
                const ev = p.evidence || {}
                return (
                  <Card key={p.id}>
                    <CardHeader className="pb-2">
                      <div className="flex items-start justify-between gap-4">
                        <div>
                          <CardTitle className="text-base">
                            {fieldLabel(p.blueprint_field)}
                          </CardTitle>
                          <CardDescription className="mt-0.5 text-xs">
                            Blueprint: {p.blueprint_id} · Niche: {nicheNameFor(p.niche_id)}
                          </CardDescription>
                        </div>
                        <div className="flex items-center gap-2 flex-shrink-0">
                          {effectBadge(ev)}
                          {tab === 'pending' && (
                            <>
                              <Button
                                size="sm"
                                disabled={busy === p.id}
                                onClick={() => handleAccept(p.id)}
                                className="bg-green-600 hover:bg-green-700 text-white"
                              >
                                <CheckCircle2 className="h-3.5 w-3.5 mr-1" />
                                Accept
                              </Button>
                              <Button
                                size="sm"
                                variant="outline"
                                disabled={busy === p.id}
                                onClick={() => handleReject(p.id)}
                              >
                                <XCircle className="h-3.5 w-3.5 mr-1" />
                                Reject
                              </Button>
                            </>
                          )}
                          {tab !== 'pending' && (
                            <Badge variant={p.status === 'accepted' ? 'default' : 'secondary'}>
                              {p.status}
                            </Badge>
                          )}
                        </div>
                      </div>
                    </CardHeader>

                    <CardContent className="pt-0 space-y-3">
                      {/* Current vs Proposed */}
                      <div className="grid grid-cols-2 gap-4 text-sm">
                        <div className="bg-gray-50 rounded p-2">
                          <p className="text-xs font-medium text-gray-500 mb-0.5">Current</p>
                          <p className="font-mono text-gray-800">{formatValue(p.current_value)}</p>
                        </div>
                        <div className="bg-green-50 rounded p-2">
                          <p className="text-xs font-medium text-gray-500 mb-0.5">Proposed</p>
                          <p className="font-mono text-gray-800">{formatValue(p.proposed_value)}</p>
                        </div>
                      </div>

                      {/* Evidence */}
                      {ev && (
                        <div className="text-xs text-gray-600 bg-blue-50 rounded p-2 space-y-1">
                          <p className="font-medium text-blue-800">Evidence</p>
                          <div className="grid grid-cols-2 gap-x-4 gap-y-0.5">
                            {ev.n_conformant !== undefined && (
                              <>
                                <span>Conformant articles</span>
                                <span className="font-mono">{ev.n_conformant}</span>
                                <span>Non-conformant articles</span>
                                <span className="font-mono">{ev.n_nonconformant}</span>
                              </>
                            )}
                            {ev.median_roi_conformant !== undefined && (
                              <>
                                <span>Median ROI (conformant)</span>
                                <span className="font-mono">{Number(ev.median_roi_conformant).toFixed(2)}×</span>
                                <span>Median ROI (non-conformant)</span>
                                <span className="font-mono">{Number(ev.median_roi_nonconformant).toFixed(2)}×</span>
                              </>
                            )}
                            {ev.ci_conformant_95 && (
                              <>
                                <span>95% CI (conformant)</span>
                                <span className="font-mono">
                                  [{ev.ci_conformant_95[0]?.toFixed(2)}, {ev.ci_conformant_95[1]?.toFixed(2)}]
                                </span>
                              </>
                            )}
                          </div>
                        </div>
                      )}

                      {/* Affected articles link */}
                      {p.niche_id && tab === 'pending' && (
                        <Link
                          to="/published"
                          className="text-xs text-blue-600 hover:underline flex items-center gap-1"
                        >
                          <TrendingUp className="h-3 w-3" />
                          View published articles in this niche
                        </Link>
                      )}

                      {p.resulting_blueprint_id && (
                        <p className="text-xs text-green-700">
                          → New Blueprint: <span className="font-mono">{p.resulting_blueprint_id}</span>
                        </p>
                      )}
                    </CardContent>
                  </Card>
                )
              })}
            </div>
          )}
        </TabsContent>
      </Tabs>

      {/* Per-niche on-demand generation */}
      {niches.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="text-sm">Generate Proposals On-Demand</CardTitle>
            <CardDescription className="text-xs">
              Run the feedback engine now for a specific niche.
              Requires at least {3} published articles per comparison bucket.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex flex-wrap gap-2">
            {niches.map((n) => (
              <Button
                key={n.id}
                variant="outline"
                size="sm"
                disabled={busy === `gen-${n.id}`}
                onClick={() => handleGenerate(n.id)}
              >
                {busy === `gen-${n.id}` ? (
                  <RefreshCw className="h-3.5 w-3.5 mr-1 animate-spin" />
                ) : (
                  <TrendingUp className="h-3.5 w-3.5 mr-1" />
                )}
                {n.name}
              </Button>
            ))}
          </CardContent>
        </Card>
      )}
    </div>
  )
}

export default FeedbackProposals
