"""Analytics + feedback-loop models (PR #7).

Five tables:

- ``article_analytics_daily``    — one row per (article, date, source).
                                   Source of truth for GSC + affiliate metrics.
- ``article_performance``        — rolled-up 28-day view per article.
                                   Refreshed after every ingest run.
- ``article_blueprint_snapshot`` — immutable audit trail binding each
                                   published article to the exact blueprint
                                   version it was evaluated against.
- ``blueprint_proposals``        — proposals to update a Blueprint field,
                                   generated by the feedback engine.
                                   Never auto-applied; human reviews + accepts.
- ``article_improvement_proposals``
                                 — per-article analog of blueprint_proposals:
                                   "this specific article is non-conformant on
                                   field X; here is the recommended change."
                                   Generated when a blueprint_proposal is
                                   accepted or on-demand.
"""
from __future__ import annotations

import json
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Optional

from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)

from src.models.user import db


# ---------------------------------------------------------------------------
# Article Analytics Daily
# ---------------------------------------------------------------------------


class ArticleAnalyticsDaily(db.Model):
    """One row per (article, date, source).

    ``source`` is one of ``'gsc'`` (Google Search Console) or
    ``'affiliate'`` (any affiliate network adapter).

    The unique constraint on ``(article_id, date, source)`` means the daily
    ingest job can safely upsert: insert-or-replace on the triple key.
    """

    __tablename__ = "article_analytics_daily"
    __table_args__ = (
        UniqueConstraint("article_id", "date", "source", name="uq_analytics_article_date_source"),
    )

    id = Column(Integer, primary_key=True)
    article_id = Column(Integer, ForeignKey("articles.id"), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)
    source = Column(String(20), nullable=False)  # 'gsc' | 'affiliate'
    impressions = Column(Integer, default=0, nullable=False)
    clicks = Column(Integer, default=0, nullable=False)
    ctr = Column(Numeric(8, 6), default=Decimal("0"), nullable=False)
    avg_position = Column(Numeric(8, 2), nullable=True)
    conversions = Column(Integer, default=0, nullable=False)
    revenue_usd = Column(Numeric(12, 4), default=Decimal("0"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "article_id": self.article_id,
            "date": self.date.isoformat() if self.date else None,
            "source": self.source,
            "impressions": self.impressions,
            "clicks": self.clicks,
            "ctr": str(self.ctr) if self.ctr is not None else "0",
            "avg_position": str(self.avg_position) if self.avg_position is not None else None,
            "conversions": self.conversions,
            "revenue_usd": str(self.revenue_usd) if self.revenue_usd is not None else "0",
        }


# ---------------------------------------------------------------------------
# Article Performance (rolled-up 28-day view)
# ---------------------------------------------------------------------------


class ArticlePerformance(db.Model):
    """28-day performance roll-up per article. Refreshed after each ingest.

    ``performance_tier`` is one of ``'winner'``, ``'mid'``, ``'loser'``,
    ``'tbd'`` (< 14 days live or insufficient data).

    The tier thresholds are niche-relative: the top 20% by ROI within a
    niche are winners, the bottom 20% are losers.
    """

    __tablename__ = "article_performance"

    article_id = Column(
        Integer, ForeignKey("articles.id"), primary_key=True, nullable=False
    )
    first_published_at = Column(DateTime, nullable=True)
    days_live = Column(Integer, default=0, nullable=False)
    total_impressions_28d = Column(Integer, default=0, nullable=False)
    total_clicks_28d = Column(Integer, default=0, nullable=False)
    avg_ctr_28d = Column(Numeric(8, 6), default=Decimal("0"), nullable=False)
    avg_position_28d = Column(Numeric(8, 2), nullable=True)
    total_epc_28d = Column(Numeric(12, 6), default=Decimal("0"), nullable=False)
    total_revenue_28d = Column(Numeric(12, 4), default=Decimal("0"), nullable=False)
    cost_usd = Column(Numeric(10, 4), default=Decimal("0"), nullable=False)
    roi = Column(Numeric(12, 4), nullable=True)   # revenue / cost; null if cost == 0
    performance_tier = Column(String(10), default="tbd", nullable=False)
    refreshed_at = Column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "article_id": self.article_id,
            "first_published_at": (
                self.first_published_at.isoformat() if self.first_published_at else None
            ),
            "days_live": self.days_live,
            "total_impressions_28d": self.total_impressions_28d,
            "total_clicks_28d": self.total_clicks_28d,
            "avg_ctr_28d": str(self.avg_ctr_28d) if self.avg_ctr_28d is not None else "0",
            "avg_position_28d": (
                str(self.avg_position_28d) if self.avg_position_28d is not None else None
            ),
            "total_epc_28d": str(self.total_epc_28d) if self.total_epc_28d is not None else "0",
            "total_revenue_28d": (
                str(self.total_revenue_28d) if self.total_revenue_28d is not None else "0"
            ),
            "cost_usd": str(self.cost_usd) if self.cost_usd is not None else "0",
            "roi": str(self.roi) if self.roi is not None else None,
            "performance_tier": self.performance_tier,
            "refreshed_at": self.refreshed_at.isoformat() if self.refreshed_at else None,
        }


# ---------------------------------------------------------------------------
# Article Blueprint Snapshot (audit trail)
# ---------------------------------------------------------------------------


class ArticleBlueprintSnapshot(db.Model):
    """Immutable record binding a published article to the exact Blueprint
    version that was in force at publish time.

    The Blueprint row may be superseded or re-versioned later; this table
    preserves what was actually used so the feedback engine's correlation
    analysis remains accurate forever.
    """

    __tablename__ = "article_blueprint_snapshots"

    id = Column(Integer, primary_key=True)
    article_id = Column(Integer, ForeignKey("articles.id"), nullable=False, index=True)
    blueprint_id = Column(String(64), nullable=False)
    blueprint_version = Column(Integer, nullable=False, default=1)
    profile_aggregate_json = Column(Text)     # full aggregate at snapshot time
    confidence_tiers_json = Column(Text)       # per-field confidence tiers
    coverage_gaps_json = Column(Text)
    snapshotted_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    def confidence_tiers(self) -> Dict[str, str]:
        try:
            return json.loads(self.confidence_tiers_json or "{}")
        except (TypeError, ValueError):
            return {}

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "article_id": self.article_id,
            "blueprint_id": self.blueprint_id,
            "blueprint_version": self.blueprint_version,
            "confidence_tiers": self.confidence_tiers(),
            "snapshotted_at": self.snapshotted_at.isoformat() if self.snapshotted_at else None,
        }


# ---------------------------------------------------------------------------
# Blueprint Proposals
# ---------------------------------------------------------------------------


class BlueprintProposal(db.Model):
    """A proposed update to one field in a Blueprint.

    Generated by the feedback engine after analysing per-Blueprint-version
    performance distributions. Never auto-applied: a human must accept or
    reject via the ``/api/proposals/<id>/accept|reject`` routes.

    On accept: a new Blueprint version is created via the PR #5a machinery.
    On reject: the row is closed and the current Blueprint is unchanged.
    """

    __tablename__ = "blueprint_proposals"

    id = Column(Integer, primary_key=True)
    niche_id = Column(Integer, ForeignKey("niches.id"), nullable=True, index=True)
    blueprint_id = Column(String(64), nullable=False)
    blueprint_field = Column(String(80), nullable=False)  # e.g. 'word_count_range'
    current_value_json = Column(Text, nullable=False)     # JSON-serialised current value
    proposed_value_json = Column(Text, nullable=False)    # JSON-serialised proposed value
    evidence_json = Column(Text, nullable=False)          # sample size, effect size, CI, articles
    generated_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    status = Column(String(20), default="pending", nullable=False)  # pending|accepted|rejected
    reviewed_by = Column(String(100), nullable=True)
    reviewed_at = Column(DateTime, nullable=True)

    # FK to the newly-created Blueprint version after accept; null until then.
    resulting_blueprint_id = Column(String(64), nullable=True)

    def current_value(self) -> Any:
        try:
            return json.loads(self.current_value_json)
        except (TypeError, ValueError):
            return self.current_value_json

    def proposed_value(self) -> Any:
        try:
            return json.loads(self.proposed_value_json)
        except (TypeError, ValueError):
            return self.proposed_value_json

    def evidence(self) -> Dict[str, Any]:
        try:
            return json.loads(self.evidence_json or "{}")
        except (TypeError, ValueError):
            return {}

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "niche_id": self.niche_id,
            "blueprint_id": self.blueprint_id,
            "blueprint_field": self.blueprint_field,
            "current_value": self.current_value(),
            "proposed_value": self.proposed_value(),
            "evidence": self.evidence(),
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "status": self.status,
            "reviewed_by": self.reviewed_by,
            "reviewed_at": self.reviewed_at.isoformat() if self.reviewed_at else None,
            "resulting_blueprint_id": self.resulting_blueprint_id,
        }


# ---------------------------------------------------------------------------
# Article Improvement Proposals (retroactive editing)
# ---------------------------------------------------------------------------


class ArticleImprovementProposal(db.Model):
    """Per-article suggestion derived from the active Blueprint.

    When a BlueprintProposal is accepted (or on-demand via
    ``generate_improvement_proposals``), the feedback engine scans
    published articles in the same niche, identifies non-conformant
    high-confidence fields, and creates one row per gap.

    The human reviews these in the ArticleReview UI. On **Apply**, the
    proposal is marked complete and Ghost-backed articles are flagged with
    ``has_unpushed_changes`` so an editor can make the recommended content
    change manually. On **Dismiss**, the row is closed with an optional reason.
    A database uniqueness constraint on ``(article_id, blueprint_field, status)``
    prevents duplicate pending proposals for the same field while still
    preserving applied/dismissed history.
    """

    __tablename__ = "article_improvement_proposals"
    __table_args__ = (
        UniqueConstraint(
            "article_id",
            "blueprint_field",
            "status",
            name="uq_improvement_proposals_article_field_status",
        ),
    )

    id = Column(Integer, primary_key=True)
    article_id = Column(Integer, ForeignKey("articles.id"), nullable=False, index=True)
    # Optional back-link to the blueprint proposal that triggered generation.
    blueprint_proposal_id = Column(Integer, ForeignKey("blueprint_proposals.id"), nullable=True)
    blueprint_field = Column(String(80), nullable=False)
    current_value_json = Column(Text, nullable=False)    # what the article currently has
    recommended_value_json = Column(Text, nullable=False) # what it should have
    rationale = Column(Text, nullable=True)
    evidence_json = Column(Text, nullable=True)
    status = Column(String(20), default="pending", nullable=False)  # pending|applied|dismissed
    dismissed_reason = Column(Text, nullable=True)
    generated_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    reviewed_at = Column(DateTime, nullable=True)

    def current_value(self) -> Any:
        try:
            return json.loads(self.current_value_json)
        except (TypeError, ValueError):
            return self.current_value_json

    def recommended_value(self) -> Any:
        try:
            return json.loads(self.recommended_value_json)
        except (TypeError, ValueError):
            return self.recommended_value_json

    def evidence(self) -> Dict[str, Any]:
        try:
            return json.loads(self.evidence_json or "{}")
        except (TypeError, ValueError):
            return {}

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "article_id": self.article_id,
            "blueprint_proposal_id": self.blueprint_proposal_id,
            "blueprint_field": self.blueprint_field,
            "current_value": self.current_value(),
            "recommended_value": self.recommended_value(),
            "rationale": self.rationale,
            "evidence": self.evidence(),
            "status": self.status,
            "dismissed_reason": self.dismissed_reason,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "reviewed_at": self.reviewed_at.isoformat() if self.reviewed_at else None,
        }


__all__ = [
    "ArticleAnalyticsDaily",
    "ArticlePerformance",
    "ArticleBlueprintSnapshot",
    "BlueprintProposal",
    "ArticleImprovementProposal",
]
